/**
 * Provides the interface for the language selector
 * in the Options tab of the map controls.
 */

import { makeStyles, MenuItem, Select, Typography } from '@material-ui/core';
import React from 'react';
import { connect } from 'react-redux';
import Flag from 'react-world-flags';

import { getLanguageOptions } from '~/components/i18n/FeatureLocalization';
import { getShortLocale, t } from '~/components/i18n/Localization';
import BorderBox from '~/components/interface/BorderBox';
import { setOverrideLang } from '~/redux/ducks/options';

const useStyles = makeStyles((_theme) => ({
  label: {
    flexGrow: 1,
  },
  flag: {
    margin: '0 8px 0 0',
  },
}));

/**
 * Renders the current value of the Language.
 * @param {*} value The locale code.
 * @param {*} label The locale name.
 * @param {*} context 'menu' or 'value'
 * @param {*} inputValue
 * @param {*} selectValue
 */
const formatFlag = (value) => {
  const classes = useStyles();

  // Flag overrides.
  let flagCode = value;
  switch (flagCode) {
    case 'en':
      // 'en' should display the United States flag.
      flagCode = 'us';
      break;
    case 'ko':
      // 'ko' should display the South Korean flag.
      flagCode = 'kr';
      break;
    case 'zh':
      // 'zh' should display the Chinese flag.
      flagCode = 'cn';
      break;
    default:
      // No override.
      break;
  }

  return <Flag code={flagCode} height={16} width={30} className={classes.flag} />;
};

// Note: The dispatchers generated by mapDispatchToProps
// shadow their associated action generators.
/* eslint-disable no-shadow */
const _MapControlsOptionsLanguage = ({ options, setOverrideLang }) => {
  const classes = useStyles();

  const langOptions = getLanguageOptions();
  const currentLangCode =
    (options?.overrideLang ?? '') !== '' ? options.overrideLang : getShortLocale();

  return (
    <BorderBox grow={false} direction="row" alignItems="center">
      <Typography className={classes.label}>{t('options-language')}</Typography>
      <Select value={currentLangCode} onChange={(event) => setOverrideLang(event.target.value)}>
        {langOptions.map((lang) => (
          <MenuItem key={lang.value} value={lang.value}>
            {formatFlag(lang.value)}
            {lang.label}
          </MenuItem>
        ))}
      </Select>
    </BorderBox>
  );
};

const mapStateToProps = (state) => ({
  options: state.options,
});
const mapDispatchToProps = (dispatch) => ({
  setOverrideLang: (lang) => dispatch(setOverrideLang(lang)),
});
const MapControlsOptionsLanguage = connect(
  mapStateToProps,
  mapDispatchToProps
)(_MapControlsOptionsLanguage);

export default MapControlsOptionsLanguage;
