import React from 'react';
import clsx from 'clsx';
import { connect } from 'react-redux';

import { MapFeatures } from '../../MapFeatures';
import { getFilterIconURL } from '../../MapFeaturesData';
import { Image } from '../../Image';
import { setFeatureDisplayed } from '../../../redux/ducks/displayed';

import './MapControlsFeatureButton.css';

/**
 * A button in the Filters, with the icon of a Map feature on it.
 * Pressing this toggles display of that Map feature.
 * @param {*} featureKey The key of the feature.
 */
// Note: The dispatchers generated by mapDispatchToProps
// shadow their associated action generators.
/* eslint-disable no-shadow */
const _MapControlsFeatureButton = ({ featureKey, active, setFeatureDisplayed }) => {
  const mapFeature = MapFeatures[featureKey];

  // Hide button if feature is not enabled.
  if (!mapFeature?.enabled) return null;

  const toggleFeature = () => {
    setFeatureDisplayed(!active);
  };

  return (
    <div
      onClick={toggleFeature}
      onKeyDown={() => {}}
      role="button"
      aria-label={mapFeature?.name}
      tabIndex={0}
      className={clsx(
        'map-controls-feature',
        active ? 'map-controls-feature-active' : '',
        'noselect'
      )}
    >
      <div className={clsx('map-controls-feature-border')}>
        <Image
          className={clsx('map-controls-feature-icon')}
          srcPNG={getFilterIconURL(mapFeature.icons.filter, 'png')}
          srcWebP={getFilterIconURL(mapFeature.icons.filter, 'webp')}
        />
      </div>
      <div className={clsx('map-controls-feature-label')}>{mapFeature.name}</div>
    </div>
  );
};

const mapStateToProps = (state, { featureKey }) => ({
  active: state.displayed?.features[featureKey] ?? false,
});
const mapDispatchToProps = (dispatch, { featureKey }) => ({
  setFeatureDisplayed: (newState) => {
    dispatch(setFeatureDisplayed(featureKey, newState));
  },
});
const MapControlsFeatureButton = connect(
  mapStateToProps,
  mapDispatchToProps
)(_MapControlsFeatureButton);

export default MapControlsFeatureButton;
