/**
 * A wrapper which handles changes to the map position.
 *
 * When the user drags the map, the position stored in Redux state should match.
 *
 * Additionally, when the user clicks the Highlight or Locate buttons, the Redux state will change.
 * This should trigger the map to pan accordingly.
 */
import React from 'react';
import { useMapEvents } from 'react-leaflet';
import { connect } from 'react-redux';

import { setPositionAndZoom } from '~/redux/ducks/ui';

// Note: The dispatchers generated by mapDispatchToProps
// shadow their associated action generators.
/* eslint-disable no-shadow */
const _MapPositionHandler = ({ mapPosition, setPositionAndZoom }) => {
  /**
   * Every time the user drags or zooms to a position on the map,
   * update the state.
   */
  const map = useMapEvents({
    dragend: () => {
      if (!map) return;
      setPositionAndZoom(map.getCenter(), map.getZoom());
    },
    zoomend: () => {
      if (!map) return;
      setPositionAndZoom(map.getCenter(), map.getZoom());
    },
  });

  /**
   * Move the map whenever the relevant state changes..
   *
   */
  React.useEffect(() => {
    if (!map) return;

    if (mapPosition.latlng !== map.getCenter() || mapPosition.zoom !== map.getZoom()) {
      map.setView([mapPosition.latlng.lat, mapPosition.latlng.lng], mapPosition.zoom, {
        animate: true,
        duration: 0.25,
        easeLinearity: 0.25,
        noMoveStart: false,
      });
    }
  }, [mapPosition]);

  // Has no render effects.
  return null;
};

const mapStateToProps = (state) => ({
  mapPosition: state.position,
});
const mapDispatchToProps = (dispatch) => ({
  setPositionAndZoom: (position, zoom) => dispatch(setPositionAndZoom(position, zoom)),
});
const MapPositionHandler = connect(mapStateToProps, mapDispatchToProps)(_MapPositionHandler);

export default MapPositionHandler;
