import _ from 'lodash';
import React from 'react';
import clsx from 'clsx';
import { connect } from 'react-redux';

import newGithubIssueUrl from 'new-github-issue-url';

import ClearEditorDataPopup from '../../popups/ClearEditorDataPopup';
import SubmitEditorDataPopup from '../../popups/SubmitEditorDataPopup';

import { setControlsTab } from '../../../redux/ducks/ui';
import { clearEditorData } from '../../../redux/ducks/editor';
import { generatePrettyJSON, openURLInWindow, setBrowserClipboard } from '../../Util';
import { useImageExtension } from '../../Image';

import MapControlsEditorMarker from './MapControlsEditorMarker';
import MapControlsEditorRoute from './MapControlsEditorRoute';

import './MapControlsEditor.css';
import { t } from '../../Localization';

// Note: The dispatchers generated by mapDispatchToProps
// shadow their associated action generators.
/* eslint-disable no-shadow */
const _MapControlsEditor = ({ displayed, editorData, resetTab, clearEditorData }) => {
  const ext = useImageExtension();

  const submitEditorData = async (formData) => {
    const dataObject = {
      ...formData,
      data: editorData.feature.data,
    };

    const jsonData = generatePrettyJSON(dataObject);

    const _result = await setBrowserClipboard(jsonData);

    const url = newGithubIssueUrl({
      user: 'genshinmap',
      repo: 'genshinmap.github.io',
      title: `[EDITOR] ${formData.name.en}`,
      body: `The following data was generated by this user using the Editor mode. Any required images should be uploaded to this issue by dragging and dropping.\n\`\`\`\nTHE EDITOR DATA SHOULD BE IN YOUR CLIPBOARD NOW. PASTE IT HERE.\n\`\`\``,
    });

    openURLInWindow(url);
  };

  return (
    <div className={clsx('map-controls-editor-container', displayed ? '' : 'display-none')}>
      <div
        className={clsx(
          'map-controls-editor-element-container',
          `map-controls-editor-element-container-${ext}`
        )}
      >
        {editorData.feature.data.map((element) => {
          const isRoute = element?.geometry?.type === 'LineString';

          return isRoute ? (
            <MapControlsEditorRoute key={element?.id} route={element} />
          ) : (
            <MapControlsEditorMarker key={element?.id} marker={element} />
          );
        })}
      </div>
      <ClearEditorDataPopup
        trigger={
          <div
            role="button"
            aria-label="Clear"
            tabIndex={0}
            className={clsx('map-controls-editor-button')}
          >
            {t('map-editor-button-clear')}
          </div>
        }
        onConfirm={() => {
          clearEditorData();
          resetTab();
        }}
      />

      <SubmitEditorDataPopup
        trigger={
          <div
            role="button"
            aria-label="Submit"
            tabIndex={0}
            className={clsx('map-controls-editor-button')}
          >
            {t('map-editor-button-submit')}
          </div>
        }
        onConfirm={submitEditorData}
      />
    </div>
  );
};

const mapStateToProps = (state) => ({
  displayed: state.controlsTab === 'elements',
  editorData: state.editor,
});
const mapDispatchToProps = (dispatch) => ({
  resetTab: () => dispatch(setControlsTab('features')),
  clearEditorData: () => dispatch(clearEditorData()),
});
const MapControlsEditor = connect(mapStateToProps, mapDispatchToProps)(_MapControlsEditor);

export default MapControlsEditor;
